In [1]:
import numpy as np

# Create a 1D Numpy array of numbers from 1 to 9

In [2]:
lst = [1,2,3,4,5,6,7,8,9,10]
a1=np.array(lst)
lst

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Create a 2D array of shape (3,3) with all elements as 1.

In [3]:
ar1=np.arange(10)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
ar1=np.ones((3,3))
print(ar1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


# Generate a Numpy array of 15 random integers between 10 and 50.

ar2=np.random.randint(10,51,size=15)
print(ar2)

# Create an array of 5 evenly spaced between 0 to 1(inclusive).

In [8]:
ar3=np.linspace(0,1,5)
print(ar3)

[0.   0.25 0.5  0.75 1.  ]


# Create a 4*4 identity matrix using Numpy.

In [13]:
a1=np.array([1,2,3,4,5,6,7,8,9,6,8,9,3,6,7,8]).reshape(4,4)
a1

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [9, 6, 8, 9],
       [3, 6, 7, 8]])

# Create an array from list[10,20,30,40] and change the datatype into float.

In [19]:
arr2=np.array([10,20,30,40],dtype=np.float64)
print(arr2)

[10. 20. 30. 40.]


# Create a 3*3 array with values from 1 to 9,then extract the second column.

In [21]:
arr=np.arange(1,10).reshape(3,3)
arr2=arr[:,1]
print(arr2)

[2 5 8]


# Create a 1D array with 10 elements and reshape into 2*5 matrix.

In [24]:
arr2=np.arange(1,11)
arr3=arr2.reshape(2,5)
print(arr3)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# Create two 2*2 matrices and perform matrix multiplication.

In [25]:
a=np.array([[1,2],
            [3,4]])
b=np.array ([[5,6],
             [7,8]])
result=np.dot(a,b)
print(result)

[[19 22]
 [43 50]]


# Given the array arr= np.array([5,12,7,18,3]).replace all values greater then 10 with 100.

In [26]:
arr5=np.array([5,12,7,18,3])
arr5[arr5 > 10]=100
print(arr5)

[  5 100   7 100   3]
